CARD_WIDTH = 1000
CARD_RADIUS = 16
CARD_TERMINAL_RADIUS = 14
CARD_HASH_LENGTH = 8
CARD_SUFFIX = ".svg"

CARD_README_DARK_MEDIA = "(prefers-color-scheme: dark)"
CARD_README_WIDTH_FULL = "100%"
CARD_README_WIDTH_TILE = "49%"
CARD_README_TILES_PER_ROW = 2
CARD_README_SPACER = "<br>"
CARD_README_HEADER = "<!--\n\n      ██╗\n      ╚██╗       hey, you're reading the source. i like you already.\n       ╚██╗\n       ██╔╝      this page and every graphic on it are generated by a\n      ██╔╝       little python in generator/, fonts and all.\n      ╚═╝        regenerate everything with `uv run readme` in there.\n           ███████╗\n           ╚══════╝  find a bug? i owe you a coffee. sadra.shameli1@gmail.com\n\n-->\n\n"
